[project]
name = "deutsch-jozsa-algo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.11.19",
    "matplotlib>=3.10.1",
    "qiskit>=1.4.1",
]
